### PR TITLE
Enhances participant API to support phone attribute

### PR DESCRIPTION
**Pull request by beneggett**
Adds tests, bumps ruby version.

### CODE REVIEW

**Comment by sampatbadhe** [comment]
Thanks for you contribution @beneggett 

I'll review and get back to you.

**Comment by beneggett** [comment]
Ok thank you. It's an easy one. I really only needed it to be read, but figured may as well enhance it to be writeable as well

**Comment by sampatbadhe** [comment]
@beneggett Thanks for adding ability to include phone number for participant.

There are few more fields are available in [Dotloop API](https://dotloop.github.io/public-api/#parameters-23), which are include in the gem. I have created an [issue](https://github.com/sampatbadhe/dotloop-ruby/issues/9) for it, would you like to include all those fields in this PR ?

**Comment by beneggett** [comment]
Sure, I can possibly look at that tomorrow. I don't know much about virtus, but as long as it can support an attribute like `"Cell Phone"`, in otherwords, it doesn't have to be a `:symbol`, then those should be very easy to add

**Comment by sampatbadhe** [comment]
@beneggett `Cell Phone` should be`:cell_phone` - I have added mapping for those attributes in the issue description. 

> I can possibly look at that tomorrow.

Sure :+1:

**Review by sampatbadhe — APPROVED** [review]
Changes looks good for `phone` field.

@beneggett I'll approve and merge this PR for now. We will add other fields in new PR.

**Comment by sampatbadhe** [comment]
@beneggett I have create [PR](https://github.com/sampatbadhe/dotloop-ruby/pull/10) for remaining participant fields. Can please take a look whenever you get the time?

**Pull request merged**
